// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

import { Asset, Entry } from "contentful";

export interface ISlideFields {
  /** mainImg */
  mainImg: Asset;

  /** Title */
  title: string;

  /** description */
  description: string;

  /** linkDemo */
  linkDemo: string;

  /** linkCode */
  linkCode: string;

  /** linkBackend */
  linkBackend?: string | undefined;
}

export declare interface ISlide extends Entry<ISlideFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "slide";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export type CONTENT_TYPE = "slide";

export type LOCALE_CODE = "en-US";

export type CONTENTFUL_DEFAULT_LOCALE_CODE = "en-US";
